/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    'blog-posts': BlogPost;
    'service-areas': ServiceArea;
    'gallery-projects': GalleryProject;
    testimonials: Testimonial;
    media: Media;
    leads: Lead;
    quotes: Quote;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'service-areas': ServiceAreasSelect<false> | ServiceAreasSelect<true>;
    'gallery-projects': GalleryProjectsSelect<false> | GalleryProjectsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Which route this content drives.
   */
  slug:
    | 'home'
    | 'about-us'
    | 'services'
    | 'design-inspirations'
    | 'quality-pricing'
    | 'gallery'
    | 'benefits'
    | 'contact-us'
    | 'resources';
  /**
   * Managed by the visual page builder. Edit at /builder — avoid hand-editing here.
   */
  layout?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  hero?: {
    eyebrow?: string | null;
    heading?: string | null;
    subheading?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Named photo slots used across the page (e.g. "story", "materialSample"). Swap any image here without touching code.
   */
  images?:
    | {
        key: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Search-engine & social-share settings. Leave blank to use smart defaults.
   */
  seo?: {
    /**
     * Browser tab & search result title. ~50–60 characters.
     */
    metaTitle?: string | null;
    /**
     * Search result snippet. ~150–160 characters.
     */
    metaDescription?: string | null;
    /**
     * Image used when the page is shared on social media (1200×630).
     */
    ogImage?: (number | null) | Media;
    /**
     * Override the canonical URL. Usually leave blank.
     */
    canonical?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for SEO & screen readers (required).
   */
  alt: string;
  /**
   * Optional photo credit / source note.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * Auto-generated from the title; edit if needed.
   */
  slug?: string | null;
  category: 'cost-guide' | 'buying-guide' | 'homeowner-tips' | 'design';
  publishedAt?: string | null;
  author?: string | null;
  /**
   * Short summary for cards & SEO.
   */
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Search-engine & social-share settings. Leave blank to use smart defaults.
   */
  seo?: {
    /**
     * Browser tab & search result title. ~50–60 characters.
     */
    metaTitle?: string | null;
    /**
     * Search result snippet. ~150–160 characters.
     */
    metaDescription?: string | null;
    /**
     * Image used when the page is shared on social media (1200×630).
     */
    ogImage?: (number | null) | Media;
    /**
     * Override the canonical URL. Usually leave blank.
     */
    canonical?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas".
 */
export interface ServiceArea {
  id: number;
  city: string;
  /**
   * URL: /siding-[slug] (e.g. san-mateo).
   */
  slug: string;
  h1: string;
  intro: string;
  heroImage?: (number | null) | Media;
  localPoints?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  closingBlurb?: string | null;
  neighborhoods?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Search-engine & social-share settings. Leave blank to use smart defaults.
   */
  seo?: {
    /**
     * Browser tab & search result title. ~50–60 characters.
     */
    metaTitle?: string | null;
    /**
     * Search result snippet. ~150–160 characters.
     */
    metaDescription?: string | null;
    /**
     * Image used when the page is shared on social media (1200×630).
     */
    ogImage?: (number | null) | Media;
    /**
     * Override the canonical URL. Usually leave blank.
     */
    canonical?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-projects".
 */
export interface GalleryProject {
  id: number;
  title: string;
  location: string;
  category: 'fiber' | 'batten' | 'cedar' | 'shingle';
  /**
   * Show in the large Home/About/Gallery feature slider.
   */
  featured?: boolean | null;
  beforeImage?: (number | null) | Media;
  afterImage?: (number | null) | Media;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  author: string;
  location?: string | null;
  projectType?: string | null;
  rating: number;
  quote: string;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  type: 'quote' | 'contact';
  status: 'New' | 'Contacted' | 'Quoted' | 'Won' | 'Lost';
  name: string;
  email: string;
  phone: string;
  address?: string | null;
  city?: string | null;
  zip?: string | null;
  interest?: string | null;
  message?: string | null;
  selection?: {
    profile?: string | null;
    texture?: string | null;
    color?: string | null;
  };
  project?: {
    sqft?: number | null;
    stories?: number | null;
  };
  estimate?: {
    low?: number | null;
    high?: number | null;
  };
  notes?: string | null;
  /**
   * Where the lead came from.
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  customerName: string;
  status: 'Draft' | 'Sent' | 'Won' | 'Lost';
  customerEmail?: string | null;
  customerPhone?: string | null;
  customerAddress?: string | null;
  sqft?: number | null;
  stories?: number | null;
  demo?: string | null;
  markup?: number | null;
  lineItems?:
    | {
        product?: string | null;
        cost?: number | null;
        qty?: number | null;
        lineTotal?: number | null;
        id?: string | null;
      }[]
    | null;
  totalCost?: number | null;
  salePrice?: number | null;
  profit?: number | null;
  /**
   * %
   */
  margin?: number | null;
  relatedLead?: (number | null) | Lead;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admins manage staff & settings. Editors manage content.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'service-areas';
        value: number | ServiceArea;
      } | null)
    | ({
        relationTo: 'gallery-projects';
        value: number | GalleryProject;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subheading?: T;
        image?: T;
      };
  images?:
    | T
    | {
        key?: T;
        image?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonical?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  publishedAt?: T;
  author?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonical?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas_select".
 */
export interface ServiceAreasSelect<T extends boolean = true> {
  city?: T;
  slug?: T;
  h1?: T;
  intro?: T;
  heroImage?: T;
  localPoints?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  closingBlurb?: T;
  neighborhoods?:
    | T
    | {
        name?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonical?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-projects_select".
 */
export interface GalleryProjectsSelect<T extends boolean = true> {
  title?: T;
  location?: T;
  category?: T;
  featured?: T;
  beforeImage?: T;
  afterImage?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  author?: T;
  location?: T;
  projectType?: T;
  rating?: T;
  quote?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  name?: T;
  email?: T;
  phone?: T;
  address?: T;
  city?: T;
  zip?: T;
  interest?: T;
  message?: T;
  selection?:
    | T
    | {
        profile?: T;
        texture?: T;
        color?: T;
      };
  project?:
    | T
    | {
        sqft?: T;
        stories?: T;
      };
  estimate?:
    | T
    | {
        low?: T;
        high?: T;
      };
  notes?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  customerName?: T;
  status?: T;
  customerEmail?: T;
  customerPhone?: T;
  customerAddress?: T;
  sqft?: T;
  stories?: T;
  demo?: T;
  markup?: T;
  lineItems?:
    | T
    | {
        product?: T;
        cost?: T;
        qty?: T;
        lineTotal?: T;
        id?: T;
      };
  totalCost?: T;
  salePrice?: T;
  profit?: T;
  margin?: T;
  relatedLead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  logo?: (number | null) | Media;
  ogDefault?: (number | null) | Media;
  promiseText?: string | null;
  /**
   * Top announcement bar text.
   */
  announcement?: string | null;
  companyName?: string | null;
  phone?: string | null;
  email?: string | null;
  hours?: string | null;
  street?: string | null;
  city?: string | null;
  region?: string | null;
  zip?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  yelp?: string | null;
  pinterest?: string | null;
  reviews?: {
    ratingValue?: number | null;
    reviewCount?: number | null;
  };
  pricing?: {
    /**
     * Sale = cost × markup
     */
    markup?: number | null;
    /**
     * Low = sale × this
     */
    rangeLow?: number | null;
    /**
     * High = sale × this
     */
    rangeHigh?: number | null;
    installMatPer1000PerStory?: number | null;
    permitsPerSqft?: number | null;
    debrisPerSqft?: number | null;
    profiles?:
      | {
          key: string;
          label: string;
          cost: number;
          install: number;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?: T;
  ogDefault?: T;
  promiseText?: T;
  announcement?: T;
  companyName?: T;
  phone?: T;
  email?: T;
  hours?: T;
  street?: T;
  city?: T;
  region?: T;
  zip?: T;
  facebook?: T;
  instagram?: T;
  yelp?: T;
  pinterest?: T;
  reviews?:
    | T
    | {
        ratingValue?: T;
        reviewCount?: T;
      };
  pricing?:
    | T
    | {
        markup?: T;
        rangeLow?: T;
        rangeHigh?: T;
        installMatPer1000PerStory?: T;
        permitsPerSqft?: T;
        debrisPerSqft?: T;
        profiles?:
          | T
          | {
              key?: T;
              label?: T;
              cost?: T;
              install?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}